version: 0.2

phases:
  pre_build:
    commands:
      - echo AWS_ACCOUNT_ID $AWS_ACCOUNT_ID
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - COMMIT_SHA=$CODEBUILD_RESOLVED_SOURCE_VERSION

      - CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)

  build:
    commands:
      - |
        if echo "$CHANGED_FILES" | grep -q "^LedgerGateway/"; then
          echo "Changes detected in LedgerGateway. Building image..."

        docker build \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ledger-gateway:latest \
          -f LedgerGateway/LedgerGateway/Dockerfile .

          docker push \
            $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ledger-gateway:latest
        else
          echo "No changes in Ledger/Gateway. Skipping build."
        fi
