version: 0.2
env:
  parameter-store:
    GITHUB_TOKEN: "LedgerCodeBuild"
    
phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing yq..."
      - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
      - yq --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - COMMIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
      - REPO_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - GITHUB_REPO=https://$GITHUB_TOKEN@github.com/AlmeidaFL/Ledger.git
      - HAS_GATEWAY_CHANGED=false
      - echo "Finishing pre build"

  build:
    commands:
      - |
        if echo "$CHANGED_FILES" | grep -q "^LedgerGateway/"; then
          echo "Changes detected in LedgerGateway. Building image..."

          docker build \
            -t $REPO_URL/ledger-gateway:latest \
            -t $REPO_URL/ledger-gateway:$COMMIT_SHA \
            -f LedgerGateway/LedgerGateway/Dockerfile .

          docker push $REPO_URL/ledger-gateway:$COMMIT_SHA
          docker push $REPO_URL/ledger-gateway:latest

          HAS_GATEWAY_CHANGED=true
        else
          echo "No changes in Ledger/Gateway. Skipping build."
        fi

  post_build:
    commands:
      - |
          echo "Configuring git config"
          git config --global user.email "deploy@ledger.com.br"
          git config --global user.name "CodeBuild Deploy"

          echo "Checking image builds to update"
          if [[ "$HAS_GATEWAY_CHANGED" = "true" ]] ; then
            echo "Updating Ledger Gateway k8s image"
            yq -i ".spec.template.spec.containers[0].image = \"$REPO_URL/ledger-gateway:$COMMIT_SHA\"" ./LedgerGateway/k8s/infra.yaml
          fi

          echo "Pushing changes"
          git add * || echo "No changes to add"
          git commit -m '[CODEBUILD] update images versions [skip ci]' || echo "No changes to commit"
          git push $GITHUB_REPO HEAD:main || echo "No changes to push"

          echo "Push concluded"

