#!/bin/bash

set -e

if [ "$#" -lt 4 ]; then
    echo "Error: Right use: $0 REPO_URL IMAGE_NAME SERVICE_NAME COMMIT_SHA INITIAL_PATH_OVERRIDE HAS_PROJECT_WITH_SOLUTION OVERRIDE_CONTEXT"
    exit 1
fi

REPO_URL=$1
IMAGE_NAME=$2
SERVICE_NAME=$3
COMMIT_SHA=$4
INITIAL_PATH_OVERRIDE=$5
HAS_PROJECT_WITH_SOLUTION=$6
OVERRIDE_CONTEXT=$7

if [[ "$INITIAL_PATH_OVERRIDE" ]]; then
  echo "Using overridden path: $INITIAL_PATH_OVERRIDE"
  DOCKERFILE_PATH="$INITIAL_PATH_OVERRIDE/$SERVICE_NAME/Dockerfile"
elif [[ "$HAS_PROJECT_WITH_SOLUTION" ]]; then
  echo "Changing path to the same as solution: $INITIAL_PATH_OVERRIDE"
  DOCKERFILE_PATH="$SERVICE_NAME/Dockerfile"
else
  echo "Using default path"
  DOCKERFILE_PATH="$SERVICE_NAME/$SERVICE_NAME/Dockerfile"
fi

CONTEXT="."
if [[ "$OVERRIDE_CONTEXT" ]]; then
    CONTEXT=$OVERRIDE_CONTEXT
fi

docker build \
  -t "$REPO_URL/$IMAGE_NAME:$COMMIT_SHA" \
  -f "$DOCKERFILE_PATH" "$CONTEXT"

docker push $REPO_URL/$IMAGE_NAME:$COMMIT_SHA