version: 0.2
env:
  parameter-store:
    GITHUB_TOKEN: "LedgerCodeBuild"
    
phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - |
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)

          if [[ "$COMMIT_AUTHOR" == "CodeBuild Deploy" ]]; then
            echo "Commit created by CodeBuild, skipping."
            exit 0
          fi

      - echo "Installing yq..."
      - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
      - chmod +x /usr/bin/yq
      - yq --version

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - COMMIT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
      - REPO_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - PRIVATE_REPO_ALIAS=private-repo
      - GITHUB_REPO=https://$GITHUB_TOKEN@github.com/AlmeidaFL/Ledger.git
      - echo "Finishing pre build"

  build:
    commands:
      - |
        chmod +x ./aws/terraform/resources/build-and-push.sh

        try_to_build() {
          local service_name=$1
          local image_name=$2
          local initial_path_override=$3
          local service_path=$1
          local has_same_path_with_solution=$4

          if [[ "$initial_path_override" ]]; then
            echo "Using overridden path: $initial_path_override"
            service_path=$3
          fi

          if echo "$CHANGED_FILES" | grep -q "^$service_path/"; then
            echo "Changes detected in $service_path. Building image..."

            ./aws/terraform/resources/build-and-push.sh "$REPO_URL" "$image_name" "$service_name" "$COMMIT_SHA" "$initial_path_override" "$has_same_path_with_solution"

            touch ".built_$service_path"
            echo "Marker file created: .built_$service_path"
          else
            echo "No changes in $service_path. Skipping build."
          fi
        }

        try_to_build "LedgerGateway" "ledger-gateway"
        try_to_build "FinancialService" "financial-service"
        try_to_build "SimpleAuth.Api" "simple-auth" "SimpleAuth"
        try_to_build "UserApi" "user-api"
        try_to_build "EventRelayWorker" "event-relay-worker" "" true

  post_build:
    commands:
      - |
          echo "Configuring git config"
          git config --global user.email "deploy@ledger.com.br"
          git config --global user.name "CodeBuild Deploy"

          echo "Checking image builds to update"

          update_k8s_image_version() {
            local service_name=$1
            local image_name=$2

            if [[ -f ".built_$service_name" ]]; then
              echo "Updating $service_name k8s image"
              yq -i "(select(.kind == \"Deployment\" or .kind == \"Job\")).spec.template.spec.containers[0].image = \"$PRIVATE_REPO_ALIAS/$image_name:$COMMIT_SHA\"" ./$service_name/k8s/infra.yaml
            else
              echo "No changes detected for $service_name"
            fi
          }

          update_k8s_image_version "LedgerGateway" "ledger-gateway"
          update_k8s_image_version "FinancialService" "financial-service"
          update_k8s_image_version "SimpleAuth" "simple-auth"
          update_k8s_image_version "UserApi" "user-api"
          update_k8s_image_version "EventRelayWorker" "event-relay-worker"

          echo "Removing created mark files"
          rm .built_LedgerGateway .built_FinancialService .built_SimpleAuth .built_UserApi .built_EventRelayWorker

          echo "Pushing changes"
          git add . || echo "No changes to add"
          git commit -m '[CODEBUILD] update images versions [skip ci]' || echo "No changes to commit"
          git push $GITHUB_REPO HEAD:main || echo "No changes to push"

          echo "Push concluded"

