#!/bin/bash

set -e

if [ "$#" -lt 4 ]; then
    echo "Error: Right use: $0 REPO_URL IMAGE_NAME DOCKERFILE_PATH COMMIT_SHA OVERRIDE_CONTEXT"
    exit 1
fi

REPO_URL=$1
IMAGE_NAME=$2
DOCKERFILE_PATH=$3
COMMIT_SHA=$4
OVERRIDE_CONTEXT=$5

CONTEXT="$DOCKERFILE_PATH"
if [[ "$OVERRIDE_CONTEXT" ]]; then
    CONTEXT=$OVERRIDE_CONTEXT
fi

docker build \
  -t "$REPO_URL/$IMAGE_NAME:$COMMIT_SHA" \
  -f "$DOCKERFILE_PATH" "$CONTEXT"

docker push $REPO_URL/$IMAGE_NAME:$COMMIT_SHA